version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REPOSITORIO}/app:development
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
    volumes:
      - ./src:/app/src

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  db_data:
